### ISSUE TITLE
Manifest instruction was reverted

### ISSUE THREAD

**Issue by berryma4** [epics-base/pvDataJava#12]
We seem to be missing this now:
https://github.com/epics-base/pvDataJava/commit/a797e73ef5740b81272e5a7f99e519d412f42c89

**Comment by anjohnson** [comment]
That change was committed to the release/4.0 branch on 2015-02-04, and specifies a rather old version of pvDataJava. I think you may have some other issues with the build since the release we're currently working on is on the release/6.0 branch and provides pvDataJava version 6.0.0. @ralphlange is the best person to advise on what's going on.

**Comment by berryma4** [comment]
Sorry for the confusion.  Around 2/4/2015 we emailed with Matej about the Manifest instruction in your pom.xml.  We asked that the name in the bundles be changed to all lower case, and in pvaccess, don't use sun.misc.  Which we agreed to instead add it as optional

```
<Bundle-SymbolicName>org.epics.pvaccess</Bundle-SymbolicName>
<Import-Package>sun.misc;resolution:=optional,*</Import-Package>
```

https://github.com/epics-base/pvAccessJava/issues/8

We would like to keep these changes for future releases.
- lower case bundle name in manifest
- don't use jre internal libraries, or at least mark optional in bundle manifest (note, internal libraries will cause issues in Java 9) 

From @kasemir

>  ... 
> Going forward, references to sun.misc will cause more trouble with Java 9.
> In theory, the "jdeps -jdkinternals ..” tool should spot calls to API that’ll go away, and this web site lists alternative API in Java 8 that’ll still be supported in Java 9:  https://wiki.openjdk.java.net/display/JDK8/Java+Dependency+Analysis+Tool
> In practice, it’s unlikely that easy.
>  ...

**Comment by ralphlange** [comment]
That change might not have been merged back to master. 
I will have a look and fix tomorrow - as I'm not doing any merges on a 5" screen... 
Which versions of pvAccess and pvData do you need this for? Do I have to release new versions, or are SNAPSHOTs good enough?

**Comment by shroffk** [comment]
A new version would be preferable...aren't you guys currently working on one. We don't mind waiting for that.

**Comment by ralphlange** [comment]
Each module is on its own numbering (numbing) scheme. What we're currently working on is a new version of the bundle. I could do new patch releases of the modules - even on old release branches - without affecting any of the bundles.

**Comment by ralphlange** [comment]
That commit had indeed never been merged back into master.
I added it (with a comment!) to the branches release/5.0 and release/6.0 and to master.

**Comment by berryma4** [comment]
Thank you so much!!!!!

**Comment by kasemir** [comment]
Yes, thanks! Matej already mentioned that the sun.misc dependency has been removed in the very latest, so no need to worry about it going forward.
